#yml的优先级低于properties
#配置配置服务器信息
server:
  port: 80
  servlet:
    context-path: /
#locahost:80/
#配置数据源信息
spring:
  datasource:
    url: jdbc:mysql:///logindb?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp

#  profiles:
  #  active: pro
mybatis:
  configuration:
    #设置session超时时间
    default-statement-timeout: 30
    #开启驼峰映射
    map-underscore-to-camel-case: true

  #配置映射文件
  mapper-locations: classpath:/mapper/*.xml
  #加入Mybatis配置-plus
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  #
  type-aliases-package: com.login.pojo
  #开启驼峰映射
  configuration:
    map-underscore-to-camel-case: true
  type-handlers-package: com.login.common.config.handler
